FROM python:3.8

WORKDIR /app
COPY ./plot_and_paper_generation ./plot_and_paper_generation
COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

CMD ["echo", "Build completed"]
