services:
  sawfish-plot-generation:
    build: 
      context: .
      dockerfile: plot_and_paper_generation/Dockerfile
    volumes:
      - ./paper/plots:/app/paper/plots
    image: sawfish-plot-generation:latest
    container_name: sawfish-plot-generation
  